/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStarWarsCharacterList } from "./IStarWarsCharacterList";
export type { StarWarsCharacterList } from "./StarWarsCharacterList";
