/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type DataTransportObjectStruct = {
  name: string;
  height: BigNumberish;
  mass: BigNumberish;
  numberOfMovies: BigNumberish;
  apiUid: BigNumberish;
};

export type DataTransportObjectStructOutput = [
  name: string,
  height: bigint,
  mass: bigint,
  numberOfMovies: bigint,
  apiUid: bigint
] & {
  name: string;
  height: bigint;
  mass: bigint;
  numberOfMovies: bigint;
  apiUid: bigint;
};

export type StarWarsCharacterStruct = {
  name: string;
  numberOfMovies: BigNumberish;
  apiUid: BigNumberish;
  bmi: BigNumberish;
};

export type StarWarsCharacterStructOutput = [
  name: string,
  numberOfMovies: bigint,
  apiUid: bigint,
  bmi: bigint
] & { name: string; numberOfMovies: bigint; apiUid: bigint; bmi: bigint };

export declare namespace IJsonApi {
  export type RequestBodyStruct = {
    url: string;
    postprocessJq: string;
    abi_signature: string;
  };

  export type RequestBodyStructOutput = [
    url: string,
    postprocessJq: string,
    abi_signature: string
  ] & { url: string; postprocessJq: string; abi_signature: string };

  export type ResponseBodyStruct = { abi_encoded_data: BytesLike };

  export type ResponseBodyStructOutput = [abi_encoded_data: string] & {
    abi_encoded_data: string;
  };

  export type ResponseStruct = {
    attestationType: BytesLike;
    sourceId: BytesLike;
    votingRound: BigNumberish;
    lowestUsedTimestamp: BigNumberish;
    requestBody: IJsonApi.RequestBodyStruct;
    responseBody: IJsonApi.ResponseBodyStruct;
  };

  export type ResponseStructOutput = [
    attestationType: string,
    sourceId: string,
    votingRound: bigint,
    lowestUsedTimestamp: bigint,
    requestBody: IJsonApi.RequestBodyStructOutput,
    responseBody: IJsonApi.ResponseBodyStructOutput
  ] & {
    attestationType: string;
    sourceId: string;
    votingRound: bigint;
    lowestUsedTimestamp: bigint;
    requestBody: IJsonApi.RequestBodyStructOutput;
    responseBody: IJsonApi.ResponseBodyStructOutput;
  };

  export type ProofStruct = {
    merkleProof: BytesLike[];
    data: IJsonApi.ResponseStruct;
  };

  export type ProofStructOutput = [
    merkleProof: string[],
    data: IJsonApi.ResponseStructOutput
  ] & { merkleProof: string[]; data: IJsonApi.ResponseStructOutput };
}

export interface StarWarsCharacterListInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "abiSignatureHack"
      | "addCharacter"
      | "characterIds"
      | "characters"
      | "getAllCharacters"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "abiSignatureHack",
    values: [DataTransportObjectStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addCharacter",
    values: [IJsonApi.ProofStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "characterIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "characters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCharacters",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "abiSignatureHack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addCharacter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "characterIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "characters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllCharacters",
    data: BytesLike
  ): Result;
}

export interface StarWarsCharacterList extends BaseContract {
  connect(runner?: ContractRunner | null): StarWarsCharacterList;
  waitForDeployment(): Promise<this>;

  interface: StarWarsCharacterListInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  abiSignatureHack: TypedContractMethod<
    [dto: DataTransportObjectStruct],
    [void],
    "view"
  >;

  addCharacter: TypedContractMethod<
    [data: IJsonApi.ProofStruct],
    [void],
    "nonpayable"
  >;

  characterIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  characters: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        name: string;
        numberOfMovies: bigint;
        apiUid: bigint;
        bmi: bigint;
      }
    ],
    "view"
  >;

  getAllCharacters: TypedContractMethod<
    [],
    [StarWarsCharacterStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "abiSignatureHack"
  ): TypedContractMethod<[dto: DataTransportObjectStruct], [void], "view">;
  getFunction(
    nameOrSignature: "addCharacter"
  ): TypedContractMethod<[data: IJsonApi.ProofStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "characterIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "characters"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        name: string;
        numberOfMovies: bigint;
        apiUid: bigint;
        bmi: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllCharacters"
  ): TypedContractMethod<[], [StarWarsCharacterStructOutput[]], "view">;

  filters: {};
}
