/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStarWarsCharacterList__factory } from "./IStarWarsCharacterList__factory";
export { StarWarsCharacterList__factory } from "./StarWarsCharacterList__factory";
