/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IStarWarsCharacterList,
  IStarWarsCharacterListInterface,
} from "../../../contracts/EventGuard.sol/IStarWarsCharacterList";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes32[]",
            name: "merkleProof",
            type: "bytes32[]",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "attestationType",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "sourceId",
                type: "bytes32",
              },
              {
                internalType: "uint64",
                name: "votingRound",
                type: "uint64",
              },
              {
                internalType: "uint64",
                name: "lowestUsedTimestamp",
                type: "uint64",
              },
              {
                components: [
                  {
                    internalType: "string",
                    name: "url",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "postprocessJq",
                    type: "string",
                  },
                  {
                    internalType: "string",
                    name: "abi_signature",
                    type: "string",
                  },
                ],
                internalType: "struct IJsonApi.RequestBody",
                name: "requestBody",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "bytes",
                    name: "abi_encoded_data",
                    type: "bytes",
                  },
                ],
                internalType: "struct IJsonApi.ResponseBody",
                name: "responseBody",
                type: "tuple",
              },
            ],
            internalType: "struct IJsonApi.Response",
            name: "data",
            type: "tuple",
          },
        ],
        internalType: "struct IJsonApi.Proof",
        name: "data",
        type: "tuple",
      },
    ],
    name: "addCharacter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllCharacters",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "numberOfMovies",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "apiUid",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "bmi",
            type: "uint256",
          },
        ],
        internalType: "struct StarWarsCharacter[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IStarWarsCharacterList__factory {
  static readonly abi = _abi;
  static createInterface(): IStarWarsCharacterListInterface {
    return new Interface(_abi) as IStarWarsCharacterListInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IStarWarsCharacterList {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IStarWarsCharacterList;
  }
}
