/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HelpersInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getFdcHub"
      | "getFdcRequestFeeConfigurations"
      | "getFlareSystemsManager"
      | "getRelay"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getFdcHub", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFdcRequestFeeConfigurations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFlareSystemsManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getRelay", values?: undefined): string;

  decodeFunctionResult(functionFragment: "getFdcHub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFdcRequestFeeConfigurations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFlareSystemsManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRelay", data: BytesLike): Result;
}

export interface Helpers extends BaseContract {
  connect(runner?: ContractRunner | null): Helpers;
  waitForDeployment(): Promise<this>;

  interface: HelpersInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFdcHub: TypedContractMethod<[], [string], "view">;

  getFdcRequestFeeConfigurations: TypedContractMethod<[], [string], "view">;

  getFlareSystemsManager: TypedContractMethod<[], [string], "view">;

  getRelay: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getFdcHub"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getFdcRequestFeeConfigurations"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getFlareSystemsManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRelay"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
