export const WALLET_CONNECT_PROJECT_ID = import.meta.env
  .VITE_WALLET_CONNECT_PROJECT_ID;
export const FLIGHT_TICKET_CONTRACT_ADDRESS = import.meta.env
  .VITE_FLIGHT_TICKET_CONTRACT_ADDRESS;
export const FAILED_KEY = "FAILED:";
export const FLIGHT_TICKET_SUBQUERY_ENDPOINT = import.meta.env
  .VITE_FLIGHT_TICKET_SUBQUERY_ENDPOINT;
export const COSTON2_DA_LAYER_URL = import.meta.env.VITE_COSTON2_DA_LAYER_URL;
export const FDC_HELPER_ADDRESS = import.meta.env.VITE_FDC_HELPER_ADDRESS;
export const BACKEND_URL = import.meta.env.VITE_BACKEND_URL;
